apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
spec:
  # SCALABILITY: Running 10 copies for High Availability
  replicas: 10
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app-container
        # Pulls the image Jenkins just built
        image: nadir468/devops-final-project:latest
        ports:
        - containerPort: 5000
        # Policy to always check for updates
        imagePullPolicy: Always
