apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  type: LoadBalancer
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 80        # The outside world connects on Port 80 (Standard Web)
      targetPort: 5000 # The container listens on Port 5000
